### PR TITLE
Use Python 3.8 in Dockerfile's entry command

### PR DESCRIPTION
**Pull request by nre-ableton**

### CODE REVIEW

**Comment by mst-ableton** [comment]
(sorry @rco-ableton, didn't see that you were a reviewer on this)

**Comment by nre-ableton** [comment]
@mst-ableton Good call for the other `python3` usage. Fixed in 049e9d7. There is no `pip3.8` though, so we have to settle for `pip3`.

**Comment by rco-ableton** [comment]
@mst-ableton no problem, I'm happy to hand this over to you since you've already started.

**Comment by nre-ableton** [comment]
@mst-ableton Ah, nevermind, got it sorted.

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Pull request merged**
