### PR TITLE
doc: example for applying codenarc.properties file

### PR DESCRIPTION
**Pull request by nre-ableton**
Contains the contents of https://github.com/AbletonDevTools/groovylint/pull/133, but also with a few formatting cleanups from my end. I've created a new PR so that we can run CI on the change, which is a requirement for merging (sorry, our CI doesn't run builds from third-party forks yet).

### CODE REVIEW

**Comment by nre-ableton** [comment]
FWIW the original changes LGTM.

**Comment by nre-ableton** [comment]
Also, mirroring @mst-ableton's post from #133, so we have it in this PR:

> Hey @pniederlag, thanks for the contribution! Could you sign our CLA (https://ableton.github.io/cla/) so we can properly review / accept it?

**Comment by nre-ableton** [comment]
Re-ping @pniederlag -- have you gotten around to signing the CLA yet?

**Comment by pniederlag** [comment]
@nre-ableton failed the first time, should have worked now :->

**Comment by nre-ableton** [comment]
@pniederlag Great! We just got the CLA and will merge shortly. Thanks again for your work!

**Comment by nre-ableton** [comment]
@ablbot rebase

**Pull request merged**
