### PR TITLE
Adapt run_codenarc.py to work with Groovy 2.5

### PR DESCRIPTION
**Pull request by nre-ableton**
These changes should still work with Groovy 2.4 as well.

---

ping @AbletonDevTools/gotham-city

### CODE REVIEW

**Comment by ala-ableton** [comment]
How do we know which Groovy version we are testing with at all?

**Comment by nre-ableton** [comment]
@ala-ableton Note the top line from the `Dockerfile`: `FROM groovy:2.4-alpine`.

@rco-ableton I have verified locally that this works with both Groovy 2.4 and 2.5. I did this by building the Docker image and running `groovylint` from it. For 2.5, I used the `run_codenarc.py` script locally and pointed `GROOVY_HOME` to brew's `groovysdk` installation, which IIRC is 2.5.4.

Also, just to be clear, we test the built Docker image on CI (see https://github.com/AbletonDevTools/groovylint/blob/master/vars/groovylint.groovy#L11). Therefore we can be reasonably certain that whatever we ship in the Docker container runs correctly.

**Comment by nre-ableton** [comment]
Oh, also, in case you were wondering, Jenkins is currently using Groovy 2.4. This can be derived by runinng `println GroovySystem.version` in the script console, which returned 2.4.11 when I tried it.

Groovy 2.5.4 is what you get with brew, and Ubuntu 16.04 ships with 2.4.5. So we should probably support 2.4 & 2.5 for as long as it is practical to do so.

**Comment by ala-ableton** [comment]
@nre-ableton please reword the commit message then. "These changes should still work" really makes me think that we are guessing.

**Comment by nre-ableton** [comment]
@ala-ableton Good point, sorry. Fixed!

**Comment by ala-ableton** [comment]
LGTM :+1:

**Pull request merged**
