### PR TITLE
Set NestedBlockDepth threshold to 8

### PR DESCRIPTION
**Pull request by nre-ableton**
NestedBlockDepth is difficult to suppress in Jenkinsfile pipelines
because @SuppressWarnings can only be used on a field, method, or
class. However, using the declarative pipeline API can easily trigger
this warning even in relatively normal use-cases.

ptal @AbletonDevTools/gotham-city, thanks!

### CODE REVIEW

**Comment by ala-ableton** [comment]
What is the default `maxNestedBlockDepth`? Please put that information in the commit message.

**Comment by nre-ableton** [comment]
@ala-ableton The default value is 5. I've added this information in the commit message body.

**Comment by ala-ableton** [comment]
LGTM :+1:

**Comment by nre-ableton** [comment]
FYI I forgot to bump the `VERSION` file, so I added another commit to this branch.

**Pull request merged**
