### PR TITLE
Change formatting to black

### PR DESCRIPTION
**Pull request by dgl-ableton**
@AbletonDevTools/gotham-city 👋

### CODE REVIEW

**Comment by nre-ableton** [comment]
Furthermore, because `pipenv` is kind of stupid, it can't update single dependencies in a file. So when you add a package and then run `pipenv lock`, it will update *everything* in that file, including other packages you may not be aware of. So the best workflow for changing the `Pipfile` is:

1. Run `pipenv lock`
2. Assuming that `Pipfile.lock` has changed, commit it to git with a generic message like "Update pipenv dependencies"
3. Edit `Pipfile`
4. Run `pipenv lock` again
5. Stage `Pipfile` and `Pipfile.lock` to git, committing them with a message about the packages you are changing.

The reason that this workflow is preferred is because if an update in some other package causes unforeseen problems, it makes it slightly easier to debug this when using `git bisect`.

**Comment by dgl-ableton** [comment]
> Almost lgtm! [f413e90](https://github.com/AbletonDevTools/groovylint/commit/f413e9065f4e29a2b5991a569c3d4e7923db4547) and [f737008](https://github.com/AbletonDevTools/groovylint/commit/f7370089bdda7e6aeac97c7cab58840ed48d674e) should be squashed together, then lgtm! You may want to consult with @nre-ableton on whether a generic "update Pipfile lock" commit is needed before doing "Add black and remove flake8-commas" (and its associated `Pipfile.lock` changes).

Update Pipfile lock commit not needed 😄

**Comment by dgl-ableton** [comment]
@ablbot rebase

**Comment by dgl-ableton** [comment]
@ablbot rebase

**Comment by dgl-ableton** [comment]
> Why is [ae1be28](https://github.com/AbletonDevTools/groovylint/commit/ae1be28b53cd588ad5f88a0cc5b8aa3b988d471a) touching `Pipfile.lock`? This doesn't feel right.

Turns out we needed to coerce `pyparsing` to not use `2.4.1`. We made another commit for this which also changes the Pipfile 😄

**Comment by nre-ableton** [comment]
I didn't dig into the diffs of the lockfile, but I wouldn't be surprised if pipenv is doing other stuff we aren't intending here. Let's just squash https://github.com/AbletonDevTools/groovylint/pull/72/commits/ebcd972045ce3c87ff7d54cdff988713a0b25a9e into https://github.com/AbletonDevTools/groovylint/pull/72/commits/83cee4d7c6d283c0e9e805dedf447eed9df33b7f (which is just as well since ebcd972045ce3c87ff7d54cdff988713a0b25a9e had a typo in the commit message 😅) and be done with it.

LGTM post squash!

**Pull request merged**
