### PR TITLE
/bin/bash doesn't exist as a shell let's use /bin/sh instead

### PR DESCRIPTION
**Pull request by v1v**
See the below error when using `--entrypoint=/bin/bash`

```
docker run --rm -v `pwd`:/ws -u `id -u`:`id -g` --entrypoint=/bin/bash  -i -t abletonag/groovylint
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

Changed to use `--entrypoint=/bin/sh` works like a charm:
```
docker run --rm -v `pwd`:/ws -u `id -u`:`id -g` --entrypoint=/bin/sh   -i -t abletonag/groovylint
/ws $ ls -l /bin/bash
ls: /bin/bash: No such file or directory
```

### CODE REVIEW

**Comment by nre-ableton** [comment]
Hi @v1v, and thanks for your PR! This change looks good, but we can't merge it without a CLA (sorry, I also realized this isn't documented yet, either 😅). Would you mind to sign [our CLA](http://ableton.github.io/cla/) and get back to us? This same CLA can be used for the other PR as well. Thanks!

**Comment by nre-ableton** [comment]
re-ping @v1v -- sorry to nag you, but would you mind signing the CLA so we can finish up and merge both of these PRs? Thanks! 🙏

**Comment by nre-ableton** [comment]
@v1v I just wanted to say that I got the CLA and will try to merge these PRs soon, probably early next week. Thanks so much! 👍

**Comment by nre-ableton** [comment]
@v1v I've cherry-picked this commit to https://github.com/AbletonDevTools/groovylint/pull/75. Our CI infrastructure doesn't yet support running third-party PRs, so I created that PR to incorporate these code changes. Do you mind if I close this PR in favor of that one?

**Comment by v1v** [comment]
Sure thing, please go ahead

**Comment by nre-ableton** [comment]
Closing in favor of https://github.com/AbletonDevTools/groovylint/pull/75

**Pull request closed without merging**
