### PR TITLE
Check that message_element has children

### PR DESCRIPTION
**Pull request by nre-ableton**
We don't want to rely on the boolean value of the XML element, which
will occur if it doesn't have any children.

---

Based on https://github.com/AbletonDevTools/groovylint/pull/106, thanks to @jfroche. Also, I've updated the commit message a bit based on changes in the code.

### CODE REVIEW

**Comment by nre-ableton** [comment]
FYI @jfroche

**Comment by nre-ableton** [comment]
Addressed in 220cb70.

**Comment by nre-ableton** [comment]
Re-ping @jfroche, can you please sign our [CLA](https://ableton.github.io/cla/)? If we don't hear from you by the 1st of March, we'll rewrite the commit ourselves.

**Comment by jfroche** [comment]
ok signed

**Comment by ala-ableton** [comment]
@ablbot rebase

**Comment by nre-ableton** [comment]
@jfroche Thanks! We'll take it from here.

**Pull request merged**
